# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule
on:
  schedule:
    - cron: '55 * * * *'
jobs:
  cron:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run:  |
          curl --request POST \
          --url 'https://yoursite.com/api/cron' \
